add.move<-function(type,ID,pgn){
  filepath<-"C:/Users/Josh/Documents/chess/chesspgn.csv"
  chesspgn<-read.csv(filepath,colClasses="character")
  newrow<-c(type,ID,pgn)
  chesspgn<-rbind(chesspgn,newrow)
  write.csv(chesspgn,
            filepath,
            row.names=FALSE)
  tail(read.csv(filepath),3)
}
