alldefinitions<-function(workdir="C:/Users/Administrator/Documents"){
  n<-1
  data<-read.definitions(n)
  while(n<length(list.files(file.path(workdir,"FDIC"),"*\\.csv"))){
    data<-rbind(data,read.definitions(n+1))
    n<-n+1
  }
  return(data)
}