notate.pgn<-function(id){
  read.pgn<-function(id){
    download.pgn<-function(id){
      URL<-paste("http://www.chess.com/echess/download_pgn?lid=",id,sep="")
      filepath<-paste("C:/Users/Josh/Documents/",id,".pgn",sep="")
      if(file.exists(filepath)==FALSE){
        dir.create(filepath)
      }
      download.file(URL,filepath)
    }
    download.pgn(id)
    pgnpath<-paste("C:/Users/Josh/Documents/",id,".pgn",sep="")
    linecol<-function(n){
      if(readLines(pgnpath)[n]==""){
        return(0)
      }
      if(!(readLines(pgnpath)[n]=="")){
        return(ncol(read.table(textConnection(readLines(pgnpath)[n]))))
      }
      grepl(readLines(pgnpath)[n],metaproperties)
    }
    lineclass<-function(n){
      if(n==length(readLines(pgnpath))){
        return("pgn")
      }
      if(n==(length(readLines(pgnpath))-1)){
        return("pgn")
      }
      if(n<(length(readLines(pgnpath))-1) & linecol(n)==3){
        return("meta")
      }
      if((n<(length(readLines(pgnpath))-1)) & (3<linecol(n))){
        return("pgn")
      }
      if(linecol(n)==0){
        return("blank")
      }
    }
    df<-data.frame(n=1:length(readLines(pgnpath)),
                   Lclass=unlist(lapply(1:length(readLines(pgnpath)),lineclass)))
    m<-subset(df$n,df$Lclass=="pgn")
    l<-min(m)
    pgn<-paste(readLines(pgnpath)[l])
    while(l<max(m)){
      pgn<-paste(pgn,readLines(pgnpath)[l+1])
      l<-(l+1)
    }
    return(pgn)
  }
  pgn<-read.pgn(id)
  pgn<-read.table(textConnection(pgn),sep=".",colClasses="character",comment.char="")
  pgn<-matrix(pgn,nrow=ncol(pgn),ncol=1)
  white<-function(n){
    n<-n+1
    as.character(read.table(textConnection(as.character(pgn[n,])),sep=" ")$V1)
  }
  black<-function(n){
    n<-n+1
    as.character(read.table(textConnection(as.character(pgn[n,])),sep=" ")$V2)
  }
  white<-unlist(lapply(1:(length(pgn)-1),white))
  black<-unlist(lapply(1:(length(pgn)-1),black))
  whitepaste<-function(n){
    paste(n,white[n],sep=".")
  }
  blackpaste<-function(n){
    paste(n,black[n],sep="...")
  }
  white<-unlist(lapply(1:length(pgn),whitepaste))
  black<-unlist(lapply(1:length(pgn),blackpaste))
  all<-c(white,black)
  all<-subset(all,grepl("NA",all)==FALSE)
  return(all)
}
