read.meta<-function(id,workdir="C:/Users/Josh/Documents"){
  filepath<-paste(workdir,"/Chess/PGN/",id,".pgn",sep="")
  if(!(file.exists(filepath))){
    download.pgn(id)
  }
  n<-1
  while(readLines(filepath)[n]!=""){
    n<-n+1
  }
  workframe<-data.frame(matrix(read.table(textConnection(readLines(filepath)[1:(n-1)]))$V2,ncol=(n-1)))
  names(workframe)<-gsub("\\[","",read.table(textConnection(readLines(filepath)[1:(n-1)]))$V1)
  workframe
}
